Sign with Docker Contents Trust

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -224,12 +224,20 @@
           run: |  
             echo "${{ secrets.DOCKER_TRUST_PRIVATE_KEY }}" > signer.key
             if [ ! -s signer.key ]; then
-            echo "Error: signer.key is empty or does not exist. Check the DOCKER_TRUST_PRIVATE_KEY secret."
+              echo "Error: signer.key is empty or does not exist. Check the DOCKER_TRUST_PRIVATE_KEY secret."
             exit 1
             fi
+            ls -l signer.key
             chmod 600 signer.key
-            docker trust key load --name signer signer.key
-            docker trust sign ${{ secrets.DOCKER_HUB_USERNAME }}/app-image:latest
+            docker trust key load --name signer signer.key || {
+              echo "Error: Failed to load key. Check the DOCKER_TRUST_PASSPHRASE secret."
+              exit 1
+            }
+
+            docker trust sign ${{ secrets.DOCKER_HUB_USERNAME }}/app-image:latest || {
+              echo "Error: Failed to sign the image. Check Docker Hub permissions and image name."
+              exit 1
+            }
           env:
             DOCKER_CONTENT_TRUST: 1
             DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.DOCKER_TRUST_PASSPHRASE }}
