New Features and improves

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -44,7 +44,9 @@
         - name: Run Bandit (SAST)
           run: |
             pip install bandit
-            bandit -r . -f txt -o bandit-report.txt || true
+            bandit -r . -f txt -o bandit-report.txt -c .bandit || true
+
+        #bandit -r . -f txt -o bandit-report.txt || true
         
         - name: Initialize CodeQL
           uses: github/codeql-action/init@v3
@@ -73,7 +75,8 @@
         - name: Run Pytest with Coverage (Pruebas Funcionales)
           run: |
             pip install pytest pytest-cov
-            pytest --cov=./ --cov-report=html
+            pytest --cov=./ --cov-report=html tests/
+
         - name: Upload Coverage Report
           uses: actions/upload-artifact@v4
           with:
@@ -143,13 +146,11 @@
         
         - name: Run Semgrep
           run: |
-             python -m pip install semgrep
-             semgrep --config=semgrep-rules/insecure-sql.yaml --sarif --output=semgrep-results.sarif . || {
-               echo "Semgrep failed, creating empty SARIF file"
-               echo '{"version": "2.1.0", "runs": [{"tool": {"driver": {"name": "Semgrep", "version": "1.0.0"}}, "results": []}]}' > semgrep-results.sarif
-             }
-          
-         ##Oldsemgrep --config=p/default --sarif --output=semgrep-results.sarif .
+            python -m pip install semgrep
+              semgrep --config=semgrep-rules/custom-sql-injection.yaml --config=semgrep-rules/insecure-sql.yaml --sarif --output=semgrep-results.sarif . || {
+                echo "Semgrep failed, creating empty SARIF file"
+                echo '{"version": "2.1.0", "runs": [{"tool": {"driver": {"name": "Semgrep", "version": "1.0.0"}}, "results": []}]}' > semgrep-results.sarif
+              }
 
         - name: Upload Semgrep SARIF to GitHub Code Scanning
           uses: github/codeql-action/upload-sarif@v3
