Zap Rules

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -94,7 +94,7 @@
         
         - name: Verify rule file exist
           run: |
-           ls -l $(pwd)/zap.conf || echo "zap.conf not found!"
+           ls -l $(pwd)/.zap/rules.tsv || echo "Rules.tsv not found!"
         
         - name: Test volume mapping
           run: |
@@ -104,11 +104,7 @@
         - name: Run OWASP ZAP Baseline Scan (DAST)
           run: |
             docker run --network host -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:latest zap-baseline.py -t http://localhost:8080 -r /zap/wrk/zap-report.html -c /zap/wrk/.zap/rules.tsv || true
-            
-        - name: Verify conf file
-          run: |
-           ls -l $(pwd)/zap.conf || echo "zap.conf missing after ZAP!"        
-
+          
         - name: Verify report generation
           run: |
            ls -l $(pwd)/zap-report.html || echo "Report not generated!"   
